# Generated by Django 4.0.2 on 2022-04-24 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='likes',
            field=models.ManyToManyField(related_name='book_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
