# Generated by Django 4.0.2 on 2022-04-24 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0005_alter_bookmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='book_post', to=settings.AUTH_USER_MODEL, verbose_name='лайкнули'),
        ),
    ]
