# Generated by Django 4.0.2 on 2022-04-27 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0006_alter_bookmodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='rating',
            field=models.ManyToManyField(null=True, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
