# Generated by Django 4.0.2 on 2022-04-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_bookmodel_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='rating',
        ),
    ]
