# Generated by Django 4.0.2 on 2022-04-30 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0011_alter_reviews_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review_name',
            field=models.ManyToManyField(related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
