# Generated by Django 4.0.2 on 2022-04-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookapp', '0012_reviews_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_name',
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
