# Generated by Django 4.0.2 on 2022-05-01 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0014_genre_alter_reviews_name_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='name_user',
            new_name='user',
        ),
    ]
