# Generated by Django 4.0.2 on 2022-05-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_remove_reviews_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='genres',
            field=models.ManyToManyField(to='bookapp.Genre', verbose_name='жанры'),
        ),
    ]
