# Generated by Django 4.0.2 on 2022-05-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0018_genre_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='url',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
    ]
