# Generated by Django 4.0.2 on 2022-05-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0019_bookmodel_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
    ]
