# Generated by Django 4.0.2 on 2022-05-04 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0021_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
