# Generated by Django 4.0.2 on 2022-05-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0022_remove_genre_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
