# Generated by Django 4.0.2 on 2022-05-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0024_alter_bookmodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='price_rent',
        ),
    ]
